language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python setup.py -q install
script:
  - python tests/run_tests.py
